apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: {{ .Values.app.namespace }}
type: Opaque
data:
  admin-user: YWRtaW4= # admin
  admin-password: cEBzc3cwcmQxMjM0NQ== # p@ssw0rd12345