apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.greetifyDbSecret.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.name }}
type: Opaque
data:
  DB_USER: {{ .Values.greetifyDbSecret.data.DB_USER }}
  SA_PASSWORD: {{ .Values.greetifyDbSecret.data.SA_PASSWORD }}