apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.greetifyValidator.service.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.name }}
    type: {{ .Values.greetifyValidator.labels.type }}
spec:
  type: {{ .Values.greetifyValidator.service.type }}
  ports:
  - port: {{ .Values.greetifyValidator.service.port }}
    targetPort: {{ .Values.greetifyValidator.service.targetPort }}
    protocol: {{ .Values.greetifyValidator.service.protocol }}
  selector:
    app: {{ .Values.app.name }}
    type: {{ .Values.greetifyValidator.labels.type }}