# If it fails to parse secret data, check the file endo f line sequence, should be "LF"
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.greetifyBackendSecret.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.name }}
type: Opaque
data:
  DB_HOST: {{ .Values.greetifyDbSecret.data.DB_HOST }}
  DB_USER: {{ .Values.greetifyDbSecret.data.DB_USER }}
  DB_PASSWORD: {{ .Values.greetifyDbSecret.data.SA_PASSWORD}}
