{{- if .Values.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.app.namespace }}
  labels:
    {{- if .Values.istioServiceMesh.enabled }}
    istio-injection: enabled
    {{- end }}
{{- end }}
