apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Values.app.namespace }}
  name: greetify-backend-binding
subjects:
- kind: ServiceAccount
  name: {{ .Values.greetifyBackend.serviceAccount.name }}
  namespace: {{ .Values.app.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.greetifyBackend.roles.name }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Values.app.namespace }}
  name: greetify-frontend-binding
subjects:
- kind: ServiceAccount
  name: {{ .Values.greetifyFrontend.serviceAccount.name }}
  namespace: {{ .Values.app.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.greetifyFrontend.roles.name }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Values.app.namespace }}
  name: greetify-validator-binding
subjects:
- kind: ServiceAccount
  name: {{ .Values.greetifyValidator.serviceAccount.name }}
  namespace: {{ .Values.app.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.greetifyValidator.roles.name }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Values.app.namespace }}
  name: greetify-db-binding
subjects:
- kind: ServiceAccount
  name: {{ .Values.greetifyDb.serviceAccount.name }}
  namespace: {{ .Values.app.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.greetifyDb.roles.name }}
  apiGroup: rbac.authorization.k8s.io
