apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.app.namespace }}
  name: {{ .Values.greetifyBackend.roles.name }}
rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
      - endpoints
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups: [""]
    resources:
      - pods/log
    verbs:
      - get
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.app.namespace }}
  name: {{ .Values.greetifyValidator.roles.name }}
rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
      - endpoints
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups: [""]
    resources:
      - pods/log
    verbs:
      - get
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.app.namespace }}
  name: {{ .Values.greetifyFrontend.roles.name }}
rules:
  - apiGroups: [""]
    resources:
      - services
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.app.namespace }}
  name: {{ .Values.greetifyDb.roles.name }}
rules:
  - apiGroups: [""]
    resources:
      - pods
      - persistentvolumeclaims
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["apps"]
    resources:
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups: [""]
    resources:
      - pods/exec
    verbs:
      - create
      - get